[package]
name = "phyx-script"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.5"
nannou = "0.19.0"
palette = "0.7.6"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
rapier2d = "0.20.0"
